### ISSUE TITLE
go module names with capital letters are awkward

### ISSUE THREAD

**Issue by olizilla** [foragepm/forage#11]
Capital letters in go module urls are replaced with ! followed by the lowercase letter e.g `github.com/shurcoo%21l/go-goon` where `%21` is the url encoded version of !.

It's a pain for anyone who wants to consume the forest api to have to thing about that munging. Let's de-munge it before returning it to the user.

**Comment by andrew** [comment]
There's a number of places we also need to go the other way, replacing capital letters with the %21lowercase versions, a micro-lib if I ever saw one.

**Comment by mvdan** [comment]
For reference, this is done by Go because it often needs to place module paths in the filesystem. And many filesystems are case-insensitive, while Go modules are case-sensitive. So all paths including module paths have to be lowercase to be properly portable (and allow caching as static content, etc).

**Comment by andrew** [comment]
Added two functions `forest.go.escape(string)` and `forest.go.unescape(string)` that'll add/remove the formatting, just need to find the best places to do the conversion.
